---
title: 'POLI210: Political Science Research Methods'
author: "Olivier Bergeron-Boutin"
date: "Fall 2021"

output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: ../template.tex
geometry: margin=1in 

email: "olivier.bergeron-boutin@mail.mcgill.ca"
officehours: "T 10-11am; W 4-5pm; F 10-11am"
office: "Zoom"
classhours: "TR 8:35am-9:55am"

ta1: "Marion Dessalles"
emailta1: "marion.dessalles@mail.mcgill.ca"
ohta1: "W 4-5"
officeta1: "Online"
ta2: "Irene Zhang"
emailta2: "peiyi.zhang@mail.mcgill.ca"
ohta2: "F 11:30-12:30"
officeta2: "Online"
ta3: "Christopher Ross"
emailta3: "christopher.ross4@mail.mcgill.ca"
ohta3: "T 1-2"
officeta3: "Leacock 520"
ta4: "Danielle Bohonos"
emailta4: "danielle.bohonos2@mail.mcgill.ca"
ohta4: "F 1:30-2:30"
officeta4: "Online"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# What is this course for? 

This course is an introduction to research methods in political science. It will cover a broad range of topics, including questions of philosophy of science; causality and the difficult enterprise of causal inference; how to ask empirical questions about the political world (and which ones to ask!); formulating empirically testable hypotheses; measurement and data collection using surveys and interviews; and qualitative and quantitative data analysis techniques designed to test your hypotheses. 

## Pre-requisites -- formal and informal 

Formal: There are no pre-requisites for enrolling in this course. However, if you have already taken POLI311, you are not eligible to take this course. For those who matriculated in the fall of 2017 or later, POLI210 serves as a prerequisite for POLI311.

Informal: You do *not* need to have a math/stats background to succeed in this course. We will provide you with the tools to succeed regardless of your background. 

## Learning outcomes 

- Become critical consumers of political science research and empirical claims in popular media. 
- Acquire knowledge of important quantitative and qualitative empirical methods in the study of politics.
- Become acquainted with *R* -- a free, open-source software that is highly marketable (this very syllabus and all course slides were created using *R*!)

# Textbook and other resources 
## Textbook

The textbook for this course will be: 

Berdahl, Loleen and Jason Roy. *Explorations: Conducting Empirical Research in  Canadian Political Science* (4th edition). Oxford University Press. 

You can purchase the print version at the McGill bookstore or rent a copy at [redshelf](https://www.redshelf.com). Note that we will be using the newer 4th edition. If you use an older edition of the textbook, it is incumbent upon you to make sure that you are not missing important material.

## Other resources

People learn in different ways and this is *especially true* when it comes to research methods. What works for me may not work for you! Fortunately, there are a lot of resources you can use: 

- StackOverflow is a Q&A forum for programmers. If you type a question related to *R* in Google, chances are that a StackOverflow thread will show up! 
- Thomas J. Leeper taught a similar course at LSE (the content of this very course is inspired by his). You can view the syllabus and slides on [his personal website](https://thomasleeper.com/designcourse/).
- *Quantitative Social Science: An Introduction* by Kosuke Imai is an excellent textbook that can help you learn *R* and principles of statistics. 
- [*R for Data Science*](https://r4ds.had.co.nz/index.html) is a free online book that introduces you to the basics of *R*/`tidyverse`.

# Remote delivery

## Lectures

The lectures will be held remotely through Zoom. They will be recorded and posted on MyCourses. 

## Labs

The labs will be held in person. You are expected to be in Montreal for the semester, but I understand that some may be unable/uncomfortable attending labs in person. As such, the labs will be recorded and posted on MyCourses. You are nonetheless encouraged to attend in person. 

## Quizzes and midterm 

The quizzes and the midterm will be available on MyCourses. See the "Evaluation policy" section for more information. 

# Labs: R and RStudio

In labs, which are expected to take place in person, you will be introduced to quantitative data analysis using the statistical software *R*, a free and open-source program. We will also be using RStudio, which is a graphical user interface that makes learning R easier. You can download *R* [here](http://www.cran.r-project.org); note that you need to choose the version that matches your operating system. You can download RStudio [here](https://www.rstudio.com/products/rstudio/download/). Try to do this as soon as possible! You will need *R* to complete most of the assignments. Your presence in labs is essential to your success in this course -- this is a skill that can only be learned by doing! 

# Optional video clips

In an effort to make the course materials more tangible, I will occasionally produce short (and hopefully fun) videos that approach things from a more informal angle. These are completely optional! This course -- and other methods courses -- is an excellent gateway into deeper, philosophical questions about the nature of knowledge. The aim is to ease your entry into the world of empirical political science by covering fun, real-world topics that would usually not be covered in a course like this. Some of the topics we may cover include: recent controversies in political science, the history of philosophy of science, how norms vary across disciplines in the social sciences, how the publication process works, what an efficient data analysis workflow looks like...Please feel free to suggest a different topic you would like to hear about! 

# MyCourses discussions

I have set up a class discussion on *MyCourses* (accessible under the "Discussions" tab). You can ask general questions about the course content, questions about the assignments, etc. *NEVER* post *R* code! I have also set up a feedback discussion that you can use if you want to provide any feedback on the course. You are welcome to post anonymously if you prefer. 

# Evaluation policy 

- Assignments: 45%. There will be 5 assignments; assignment 1 is worth 5 points; assignments 2 through 5 are worth 10 points each. You are allowed to talk generally about the problem sets with your classmates, but you are expected to complete them individually. *You cannot share code with your classmates*.
  - Assignment 1, due on September 20th at 11:59pm, will simply ask to fill in a class survey on the platform *Qualtrics*. The data you provide here will be of use to create some interactive examples in class!
  - Assignment 2, due on October 7th at 11:59pm, will ask you to perform basic operations in *R* using the class survey: compute measures of central tendency, recoding variables, describing distributions. 
  - Assignment 3, due on October 25th at 11:59pm, will ask you to work with experimental data from a famous political science article. It will address issues of causality. 
  - Assignment 4, due on November 17th at 11:59pm, will focus on the case-study and comparative approaches. 
  - Assignment 5, due on December 2nd at 11:59pm, will ask you to work with data from the 2019 Canadian Election Study and will focus on comparisons between means, p-values, multivariate regression.
- Quizzes: 15%. The first quiz will be posted to the "Quiz" section on MyCourses on Monday October 25th and you will need to complete it by Wednesday October 27th, 11:59pm. The second quiz will be posted on Thursday December 2nd and you will need to complete it by Friday December 17th, 11:59pm. Each is worth 7.5%. Anything covered in lectures or in the readings is fair game; the format is multiple choice questions. Once you have opened the quiz, you will have 1.5 hour to complete it. 
- Midterm: 20%. The midterm will be posted on MyCourses on Tuesday November 9th and you will need to submit your answers by Friday November 12th, 11:59pm. Everything up to the material from week 10 (inclusively) is fair game. You are allowed to use any course materials, but you are expected to complete the midterm on an individual basis. Once you have opened the midterm, you will have 3 hours to complete it. 
- Team project: 20%. Due on December 6th at 11:59pm. In teams of four, you will choose a political science article from a pre-approved list that will span the subfields of the discipline as well as the methodological approaches we will have covered in this course. You will first have to answer basic questions about the article: what is the research question? What is the hypothesis? Then, you will be asked to take a more critical approach and assess the methodological merits of the article. What are the main threats to inference and how well do the authors defend their research design? More details will be given in class in November. 

# Submissions

Everything will be handled remotely. These are the instructions for each component:

- Quizzes: The quizzes will be available on MyCourses under the tab "Quizzes."
- Midterm: The midterm will be posted on MyCourses and you will be able too upload the finished product under the "Assignments" tab. 
- Assignments: You will be able to upload your work under the "Assignments" tab. For the assignments involving R, you need to upload both your R script (.R file) as well as your written answers (in a PDF or Word document). 

# Course and University policies

## Lanuage of submission
In accord with McGill University’s Charter of Student Rights, students in this course have the right to submit in English or in French any written work that is to be graded. This does not apply to courses in which acquiring proficiency in a language is one of the objectives.” (Approved by Senate on 21 January 2009) 

## Academic integrity
McGill University values academic integrity. Therefore, all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the Code of [Student Conduct and Disciplinary Procedures](https://www.mcgill.ca/secretariat/files/secretariat/code_of_student_conduct_and_disciplinary_procedures.pdf).

## Copyright
© Instructor-generated course materials (e.g., handouts, notes, summaries, exam questions) are protected by law and may not be copied or distributed in any form or in any medium without explicit permission of the instructor. Note that infringements of copyright can be subject to follow up by the University under the Code of Student Conduct and Disciplinary Procedures.

## Late submission

Late assignments will be penalized 5 percentage points (out of 100) per day. Late quizzes will not be accepted.  Exceptions apply for illness, family emergency, or other extraordinary circumstances. You will need to provide documentation of your predicament and will be given more time to complete your assignment/quiz.

## Re-grading

Students who wish to contest a grade for an assignment or exam must do so in writing (by email, sent to the instructor) providing the reasoning behind their challenge to the grade received within two weeks of the day on which the assignments are returned. The TA who graded the assignment will re-grade your assignment, and may raise or lower the grade. If you are still unsatisfied after the re-assessment, you can re-submit the assignment to me (original copy with TA comments), along with your justification. I will then re-evaluate the assignment, but also reserve the right to raise or lower the grade. Please also see [the department's guidelines](http://www.mcgill.ca/politicalscience/files/politicalscience/assessment_and_
re-read_policy_final.pdf).

# Class schedule

**Week 1**: Intro

\setlength{\leftskip}{1cm}
+ Lecture 1.1 (Sept 2nd): Reviewing the syllabus and course components. Differentiating between two types of social scientific research (normative vs empirical). Three types of inference in empirical research (causal, descriptive, predictive). 

+ Readings: None. 

\setlength{\leftskip}{0cm}
**Week 2**: The foundations of scientific research

\setlength{\leftskip}{1cm}
+ Lecture 2.1 (Sept 7th): We will cover some foundational questions: What makes science scientific? What are the principles of scientific research? 

+ Lecture 2.2 (Sept 9th): The steps in the scientific process. Quantitative and qualitative approaches. How a scientist behaves. 

+ Readings: 
  + *Explorations* chapters 1. 
  + [The Supreme Court is Allergic to Math](https://fivethirtyeight.com/features/the-supreme-court-is-allergic-to-math/), FiveThirtyEight. 
  + [The social sciences are useless. So why do we study them?](https://statmodeling.stat.columbia.edu/2021/03/12/the-social-sciences-are-useless-so-why-do-we-study-them-heres-a-good-reason/), by Andrew Gelman. 
  + Noel, Hans. 2010. “Ten Things Political Scientists Know That You Don’t.” The Forum 8(3).
  
\setlength{\leftskip}{0cm}
**Week 3**: Building theory and making hypotheses

\setlength{\leftskip}{1cm}
+ Lecture 3.1 (Sept 14th): What is a scientific "literature"? How do we come up with a research question, and what makes for a good one? How to build theory: inductive vs deductive approaches. Formulating hypotheses. Hypothesis testing and refining theory.

+ Lecture 3.2 (Sept 16th): Library workshop. 

+ Readings: 
  + *Explorations* chapters 2 (full) and 4 (pp.55-58). 
  + Mutz, Diana C., and Jahnavi S. Rao. 2018. “The Real Reason Liberals Drink Lattes.” *PS: Political Science & Politics* 51(4): 762–67.
  
\setlength{\leftskip}{0cm}
**Week 4**: Causality

\setlength{\leftskip}{1cm}
+ Lecture 4.1 (Sept 21st): Introduction to the potential outcomes framework and the fundamental problem of causal inference. Thinking counterfactually. Causal vs correlational relationships. 

+ Lecture 4.2 (Sept 23rd): How random assignment solves the problem of self-selection. Experimental methods in political science. Internal vs external validity. The search for quasi-experiments.

+ Readings: 
  + Druckman, James N., Donald P. Greene, James H. Kuklinski, and Arthur Lupia. 2011. “Experiments.” In *Cambridge Handbook of Experimental Political Science*, Cambridge: Cambridge University Press, 15–26.
  + *Explorations* chapter 9. 
  +  Butler, Daniel M., and David E. Broockman. 2011. “Do Politicians Racially Discriminate Against Constituents? A Field Experiment on State Legislators.” *American Journal of Political Science* 55(3): 463–77.

  
\setlength{\leftskip}{0cm}
**Week 5**: Conceptualization and measurement

\setlength{\leftskip}{1cm}
+ Lecture 5.1 (Sept 28th): Why do we even need concepts? How do define concepts? How do we differentiate one concept from another? The ladder of generality and "definitional gerrymandering"

+ Lecture 5.2 (Sept 30th): 4 levels of measurement. Measurement obstacles: random and non-random measurement error; social desirability bias. Measurement validity.

+ Readings: 
  + *Explorations* chapter 4 (pp.58-66).
  + Choose one:
    + Collier, David, and Steven Levitsky. 1997. “Democracy with Adjectives: Conceptual Innovation in Comparative Research.” *World Politics* 49(3): 430–51.
    + Mansbridge, Jane. 2003. “Rethinking Representation.” *American Political Science Review* 97(4): 515–28.
    + Lueders, Hans, and Ellen Lust. 2018. “Multiple Measurements, Elusive Agreement, and Unstable Outcomes in the Study of Regime Change.” *The Journal of Politics* 80(2): 736–41.

  
\setlength{\leftskip}{0cm}
**Week 6**: Case studies and the comparative method

\setlength{\leftskip}{1cm}
+ Lecture 6.1 (Oct 5th): Two types of case studies: descriptive vs theory-testing. Why focus on a single case? Scope conditions and generalization to other cases. What sort of evidence do we use? 

+ Lecture 6.2 (Oct 7th): Goals of the comparative method. How to select cases: purposive sampling. Mill's method of similarity and method of difference. Can we establish causal relations? 

+ Readings: 
  + *Explorations* chapter 10.
  + Geddes, Barbara. 1990. “How the Cases You Choose Affect the Answers You Get: Selection Bias in Comparative Politics.” Political Analysis 2: 131–50.

\setlength{\leftskip}{0cm}
**Week 7**: Interviews and focus groups

\setlength{\leftskip}{1cm}
+ Lecture 7.1 (Oct 15th): Guest lecture by Professor Tania Islas Weinstein. 

+ Readings: 
  + *Explorations* chapter 7. 
  + Fujii, Lee Ann. 2018. Interviewing in social science research: a relational approach (Routledge): ch. 1 & 4 (pp. 1-11 & 53-72).


\setlength{\leftskip}{0cm}
**Week 8**: Ethnography and the interpretive method + survey research I. 

\setlength{\leftskip}{1cm}
+ Lecture 8.1 (Oct 19th): Ethnography/interpretive method.

+ Lecture 8.2 (Oct 21st): A short history of political polling. How do we sample for polls? 

+ Readings: 
  + *Explorations* chapter 5.
  
\setlength{\leftskip}{0cm}
**Week 9**: Survey research II + descriptive statistics. 

\setlength{\leftskip}{1cm}
+ Lecture 9.1 (Oct 26th): The promises and pitfalls of survey research. What happened in 2016 and 2020 -- are polls broken?

+ Lecture 9.2 (Oct 28th):  Measures of central tendency and measures of variance. Confidence intervals. The central importance of distributions. 

+ Readings: 
  + *Explorations* chapter 8.
  
\setlength{\leftskip}{0cm}
**Week 10**: The basics of statistical inference and hypothesis testing. 

\setlength{\leftskip}{1cm}
+ Lecture 10.1 (Nov 2nd): Measures of association for different types of variables. Linear vs non-linear relationships. 

+ Lecture 10.2 (Nov 4th): Difference-in-means and hypothesis testing. p-values and what they do/don't tell you. 

+ Readings: 
  + *Explorations* chapter 12.
  
\setlength{\leftskip}{0cm}
**Week 11**: Research ethics and the replication crisis

\setlength{\leftskip}{1cm}
+ Lecture 11.1 (Nov 9th): Research ethics and the replication crisis. Advances in research transparency: public data, pre-registration, registered reports. 

+ Lecture 11.2 (Nov 11th): No class (complete midterm). 

+ Readings: 
  + *Explorations* chapter 3.
  + Lee, Stephanie M. 2018. "[Here’s How Cornell Scientist Brian Wansink Turned Shoddy Data Into Viral Studies About How We Eat.](https://www.buzzfeednews.com/article/stephaniemlee/brian-wansink-cornell-p-hacking#.qs6A0K3DW)" *Buzzfeed News*. 
  + Singal, Jesse. 2015. "[The Case of the Amazing Gay-Marriage Data: How a Graduate Student Reluctantly Uncovered a Huge Scientific Fraud.](https://www.thecut.com/2015/05/how-a-grad-student-uncovered-a-huge-fraud.html)" *New York Magazine*.

\setlength{\leftskip}{0cm}
**Week 12**: Linear regression

\setlength{\leftskip}{1cm}
+ Lecture 12.1 (Nov 16th): The least squares algorithm and its mechanics.  

+ Lecture 12.2 (Nov 18th): Interpreting regression output. Substantive vs statistical significance. 

+ Readings: 
  + *Explorations* chapter 13.
  
\setlength{\leftskip}{0cm}
**Week 13**: More on regression + mixed methods. 

\setlength{\leftskip}{1cm}
+ Lecture 13.1 (Nov 23rd): Basic regression diagnostics. What linear regression does and doesn't tell you about the political world. A short word on mixed methods. 

+ Lecture 13.2 (Nov 25th): Preparation for the final project: how should we read empirical political science articles? How do we tell whether we should trust the findings? 

+ Readings: 
  + *Explorations* chapter 14 (optional).

\setlength{\leftskip}{0cm}
**Week 14**: Wrapping up

\setlength{\leftskip}{1cm}
+ Lecture 14.1 (Nov 30th): Review session. 

+ Lecture 14.2 (Dec 2nd): Empirical political science today -- what *haven't* we learned in this class? 

+ Readings: 
  + None. 

